//const db = require('../db');
//----------------------------------------------------
const UsuarioService = require('../services/usuarioService');
const usuarioService = new UsuarioService();
//----------------------------------------------------

const { hashPassword, matchPassword } = require('../security/hashPass');
const { generarToken } = require('../security/token');

//----------------------------------------------------
const AppError = require('../utilits/helpers/errors');

class AuthController{

    static async loginUsuario(usuario, password) {
        try {
        const user = await usuarioService.existeByUsuario(usuario);
        //console.log("üß† Usuario para token:", user.toJSON());
        if (!user) {
            throw new AppError('Usuario no encontrado', 404);
        }
        const isPasswordValid = await matchPassword(password, user.password);
        if (!isPasswordValid) {
            throw new AppError('Contrase√±a incorrecta', 401);
        }
        //console.log('Usuario encontrado:', user.id_usuario);
        // Generar el token de sesi√≥n
        const token = await generarToken(user.toJSON());
        return { ...user.toJSON(), token: token };
        } catch (error) {  
            console.error('Error en loginUsuario:', error);
            if (error instanceof AppError) {
                throw error; // Propagar el error personalizado
            }
            throw new AppError('Error al iniciar sesi√≥n', 500, error.message);
            
        }
    };

    static async registrarUsuario(data, password) {
        try {
          const existingUser = await usuarioService.existeByUsuario(
            data.usuario
          );
          if (existingUser) {
            throw new AppError("El usuario ya existe", 409);
          }
          const hashedPassword = await hashPassword(password);
          const newUser = await usuarioService.create({
            ...data,
            password: hashedPassword,
          });
          //console.log("üß† Usuario para token:", newUser.toJSON());
          const token = await generarToken(newUser.toJSON());
          if (!token) {
            throw new AppError("Error al generar el token", 500);
          }
          return { ...newUser.toJSON(), token: token };
        } catch (error) {
            console.error('Error en registrarUsuario:', error);
            if (error instanceof AppError) {
                throw error; // Propagar el error personalizado
            }
            throw new AppError('Error al registrar usuario', 500, error.message);
        }
    };

    static async logout(req, res) {
        try {
            return res.status(200).json({ message: 'Sesi√≥n cerrada exitosamente' });
        } catch (error) {
            console.error('‚ùå Error al cerrar sesi√≥n:', error);
            if (error instanceof AppError) {
                return res.status(error.statusCode).json({ message: error.message });
            }
            return res.status(500).json({ message: 'Error interno del servidor', error: error.message });
            
        }
    };
}

module.exports = AuthController;